version: build{build}
image: Visual Studio 2017

branches:
  only:
  - master

build:
  parallel: true
  verbosity: detailed

environment:
  global:
    ARCH: x64
    QMAKESPEC: win32-msvc
    MAKETOOL: jom
    TOOLSDIR: C:\Qt\Tools\QtCreator
  matrix:
    - QTDIR: C:\Qt\5.9\msvc2017_64

configuration:
  - release

install:
  - set OPENSSL_DIR="C:\OpenSSL-Win64"
  - set ICU_DIR_NAME=icu4c-54_1-Win64-msvc10
  - set ICU_DOWNLOAD_URL="http://download.icu-project.org/files/icu4c/54.1/%ICU_DIR_NAME%.zip"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - set PATH=%QTDIR%\bin;%TOOLSDIR%\bin;%OPENSSL_DIR%\bin;%CD%\bin;%PATH%

build_script:
  - echo "BUILD %APPVEYOR_BUILD_VERSION%_%QMAKESPEC%_%CONFIGURATION%_%ARCH%_%appveyor_repo_tag_name%"
  - qmake CONFIG+=%CONFIGURATION% INCLUDEPATH+="%OPENSSL_DIR%\include" LIBS+=-L%OPENSSL_DIR%\lib quiterss2.pro
  - call %MAKETOOL%
  - ls

after_build:
  - 7z a "QuiteRSS.zip" "release\*"

artifacts:
  - path: QuiteRSS.zip
    name: QuiteRSS-archive
  - path: release\*.exe
    name: QuiteRSS-executable

deploy:
- provider: BinTray
  username: funcy-dcm
  api_key:
    secure: pHgpq9FPGqcuEERtIZJAEvkEXUzl2OwVmcw4j8z5ndngGXBGRiRXzbBBTSAFef5n
  subject: funcy-dcm
  repo: QuiteRSS/quiterss2
  package: quiterss2
  publish: true
  override: true
#  artifact: QuiteRSS-archive