version: build{build}-{branch}
image: Visual Studio 2017

build:
  parallel: true
  verbosity: detailed

environment:
  global:
    APP_VERSION: 2.0.0
    ARCH: x64
    QMAKESPEC: win32-msvc
    MAKETOOL: jom
    TOOLSDIR: C:\Qt\Tools\QtCreator
  matrix:
    - QTDIR: C:\Qt\5.9\msvc2017_64

configuration:
  - release

install:
  - if "%APPVEYOR_REPO_TAG%" == "true" set APPVEYOR_BUILD_VERSION=%APPVEYOR_REPO_TAG_NAME%
  - set OPENSSL_DIR="C:\OpenSSL-Win64"
  - set ICU_DIR_NAME=icu4c-54_1-Win64-msvc10
  - set ICU_DOWNLOAD_URL="http://download.icu-project.org/files/icu4c/54.1/%ICU_DIR_NAME%.zip"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - set PATH=%QTDIR%\bin;%TOOLSDIR%\bin;%OPENSSL_DIR%\bin;%CD%\bin;%PATH%

build_script:
  - echo "BUILD %APPVEYOR_BUILD_VERSION%_%QMAKESPEC%_%CONFIGURATION%_%ARCH%_%APPVEYOR_REPO_TAG_NAME%"
  - qmake CONFIG+=%CONFIGURATION% INCLUDEPATH+="%OPENSSL_DIR%\include" LIBS+=-L%OPENSSL_DIR%\lib quiterss2.pro
  - call %MAKETOOL%
  - ls

after_build:
  - 7z a "QuiteRSS-%APPVEYOR_BUILD_VERSION%.zip" "release\*"
  - 7z a "QuiteRSS-%APPVEYOR_BUILD_VERSION%-setup.zip" "release\quiterss2.exe"

artifacts:
  - path: QuiteRSS-%APPVEYOR_BUILD_VERSION%.zip
    name: QuiteRSS-portable
  - path: QuiteRSS-%APPVEYOR_BUILD_VERSION%-setup.zip
    name: QuiteRSS-setup

deploy:
- provider: BinTray
  username: funcy-dcm
  api_key:
    secure: pHgpq9FPGqcuEERtIZJAEvkEXUzl2OwVmcw4j8z5ndngGXBGRiRXzbBBTSAFef5n
  subject: quiterss
  repo: quiterss2
  package: Windows-installer
  version: $(APPVEYOR_BUILD_VERSION)
  publish: true
  override: true
  artifact: QuiteRSS-setup
  on:
    appveyor_repo_tag: true
  
- provider: BinTray
  username: funcy-dcm
  api_key:
    secure: pHgpq9FPGqcuEERtIZJAEvkEXUzl2OwVmcw4j8z5ndngGXBGRiRXzbBBTSAFef5n
  subject: quiterss
  repo: quiterss2
  package: Windows-portable
  version: $(APPVEYOR_BUILD_VERSION)
  publish: true
  override: true
  artifact: QuiteRSS-portable
  on:
    appveyor_repo_tag: true
  
- provider: BinTray
  username: funcy-dcm
  api_key:
    secure: pHgpq9FPGqcuEERtIZJAEvkEXUzl2OwVmcw4j8z5ndngGXBGRiRXzbBBTSAFef5n
  subject: quiterss
  repo: quiterss2-development
  package: Windows-portable-dev
  version: $(APPVEYOR_BUILD_VERSION)
  publish: true
  override: true
  artifact: QuiteRSS-portable
  on:
    branch: master