version: build{build}-{branch}
image: Visual Studio 2017

cache:
  - C:\OpenSSL-Win64

build:
  parallel: true
  verbosity: detailed

environment:
  global:
    ARCH: x64
    QMAKESPEC: win32-msvc
    MAKETOOL: jom
    TOOLSDIR: C:\Qt\Tools\QtCreator
  matrix:
    - QTDIR: C:\Qt\5.9\msvc2017_64

configuration:
  - release

install:
  - if "%APPVEYOR_REPO_TAG%" == "true" set APPVEYOR_BUILD_VERSION=%APPVEYOR_REPO_TAG_NAME%
  - set OPENSSL_DIR="C:\OpenSSL-Win64"
#  - IF NOT EXIST "%OPENSSL_DIR%\bin" ( appveyor DownloadFile %ICU_DOWNLOAD_URL% ) else ( echo "Use cached %ICU_DIR_NAME%.zip")
  - appveyor DownloadFile https://slproweb.com/download/Win64OpenSSL_Light-1_1_0f.exe
  - Win64OpenSSL_Light-1_1_0f.exe /silent /verysilent /sp- /suppressmsgboxes
  - ls %OPENSSL_DIR%
  - ls %OPENSSL_DIR%\bin
  - set ICU_DIR_NAME=icu4c-54_1-Win64-msvc10
  - set ICU_DOWNLOAD_URL="http://download.icu-project.org/files/icu4c/54.1/%ICU_DIR_NAME%.zip"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - set PATH=%QTDIR%\bin;%TOOLSDIR%\bin;%OPENSSL_DIR%\bin;%CD%\bin;%PATH%

build_script:
  - echo "BUILD %APPVEYOR_BUILD_VERSION%_%QMAKESPEC%_%CONFIGURATION%_%ARCH%_%APPVEYOR_REPO_TAG_NAME%"
  - mkdir build && cd build
  - qmake CONFIG+=%CONFIGURATION% INCLUDEPATH+="%OPENSSL_DIR%\include" LIBS+=-L%OPENSSL_DIR%\lib ..\quiterss2.pro
  - call %MAKETOOL%
  - windeployqt bin\quiterss.exe --qmldir=..\resources\qml
  - cd bin
  - cp c:\Windows\SysWOW64\msvcp140.dll .
  - cp c:\Windows\SysWOW64\vccorlib140.dll .
  - cp c:\Windows\SysWOW64\vcruntime140.dll .
  - ls C:\OpenSSL-Win64
  - ls C:\OpenSSL-Win64\bin
  - 7z a "QuiteRSS-%APPVEYOR_BUILD_VERSION%.zip" "*"
  - 7z a "QuiteRSS-%APPVEYOR_BUILD_VERSION%-setup.zip" "quiterss.exe"

artifacts:
  - path: build\bin\QuiteRSS-%APPVEYOR_BUILD_VERSION%.zip
    name: QuiteRSS-portable
  - path: build\bin\QuiteRSS-%APPVEYOR_BUILD_VERSION%-setup.zip
    name: QuiteRSS-setup

deploy:
- provider: BinTray
  username: funcy-dcm
  api_key:
    secure: pHgpq9FPGqcuEERtIZJAEvkEXUzl2OwVmcw4j8z5ndngGXBGRiRXzbBBTSAFef5n
  subject: quiterss
  repo: quiterss2
  package: Windows-installer
  version: $(APPVEYOR_BUILD_VERSION)
  publish: true
  override: true
  artifact: QuiteRSS-setup
  on:
    appveyor_repo_tag: true
  
- provider: BinTray
  username: funcy-dcm
  api_key:
    secure: pHgpq9FPGqcuEERtIZJAEvkEXUzl2OwVmcw4j8z5ndngGXBGRiRXzbBBTSAFef5n
  subject: quiterss
  repo: quiterss2
  package: Windows-portable
  version: $(APPVEYOR_BUILD_VERSION)
  publish: true
  override: true
  artifact: QuiteRSS-portable
  on:
    appveyor_repo_tag: true
  
- provider: BinTray
  username: funcy-dcm
  api_key:
    secure: pHgpq9FPGqcuEERtIZJAEvkEXUzl2OwVmcw4j8z5ndngGXBGRiRXzbBBTSAFef5n
  subject: quiterss
  repo: quiterss2-development
  package: Windows-portable-dev
  version: $(APPVEYOR_BUILD_VERSION)
  publish: true
  override: true
  artifact: QuiteRSS-portable
  on:
    branch: master
