version: build{build}
image: Visual Studio 2017

cache:
  - windows/dependencies

build:
  parallel: true
  verbosity: detailed

environment:
  global:
    ARCH: x64
    QMAKESPEC: win32-msvc
    MAKETOOL: jom
    TOOLSDIR: C:\Qt\Tools\QtCreator
  matrix:
    - QTDIR: C:\Qt\5.9\msvc2017_64

configuration:
  - release

install:
  - set OPENSSL_DIR="C:\OpenSSL-Win64"
  - set ICU_DIR_NAME=icu4c-54_1-Win64-msvc10
  - set ICU_DOWNLOAD_URL="http://download.icu-project.org/files/icu4c/54.1/%ICU_DIR_NAME%.zip"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %ARCH%
  - set PATH=%QTDIR%\bin;%TOOLSDIR%\bin;%OPENSSL_DIR%\bin;%CD%\bin;%PATH%

build_script:
  - echo "BUILD %APPVEYOR_BUILD_VERSION%_%QMAKESPEC%_%CONFIGURATION%_%ARCH%"
  - qmake -v
  - qmake CONFIG+=%CONFIGURATION% INCLUDEPATH+="%OPENSSL_DIR%\include" LIBS+=-L%OPENSSL_DIR%\lib quiterss2.pro
  - call %MAKETOOL%