version: build{build}-{branch}
image: Visual Studio 2015

build:
  parallel: true
  verbosity: detailed

environment:
  global:
    ARCH: x86
    TOOLSDIR: C:\Qt\Tools\QtCreator
  matrix:
  - PORTABLE: "true"
    QTDIR: C:\Qt\5.9\msvc2015
  - ARCH: x86
    QTDIR: C:\Qt\5.9\msvc2015
  - ARCH: x64
    QTDIR: C:\Qt\5.9\msvc2015_64

configuration:
  - release

install:
  - if "%APPVEYOR_REPO_TAG%" == "true" (set APPVEYOR_BUILD_VERSION=%APPVEYOR_REPO_TAG_NAME%)
  - set CPU=32
  - if "%ARCH%" == "x64" (set CPU=64)
  - set OPENSSL_DIR="C:\OpenSSL-Win%CPU%"
  - set ICU_DIR_NAME=icu4c-54_1-Win%CPU%-msvc10
  - set ICU_DOWNLOAD_URL="http://download.icu-project.org/files/icu4c/54.1/%ICU_DIR_NAME%.zip"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
  - set PATH=%QTDIR%\bin;%TOOLSDIR%\bin;%OPENSSL_DIR%\bin;%CD%\bin;%PATH%

build_script:
  - echo "BUILD %APPVEYOR_BUILD_VERSION%_%CONFIGURATION%_%ARCH%_%APPVEYOR_REPO_TAG_NAME%"
  - mkdir build && cd build
  - qmake CONFIG+=%CONFIGURATION% INCLUDEPATH+="%OPENSSL_DIR%\include" LIBS+=-L%OPENSSL_DIR%\lib ..\quiterss2.pro
  - call jom
  - windeployqt bin\quiterss.exe --qmldir=..\resources\qml
  - cp c:\Windows\SysWOW64\msvcp140.dll .\bin
  - cp c:\Windows\SysWOW64\vccorlib140.dll .\bin
  - cp c:\Windows\SysWOW64\vcruntime140.dll .\bin
  - cp %OPENSSL_DIR%\libeay32.dll .\bin
  - cp %OPENSSL_DIR%\ssleay32.dll .\bin
  - cp ..\AUTHORS .\bin
  - cp ..\CHANGELOG .\bin
  - cp ..\LICENSE .\bin
  - cp ..\README.md .\bin
  - cmd: |
     if "%PORTABLE%" == "true" (
        echo "test"
        echo ls
        mkdir QuiteRSS-%APPVEYOR_BUILD_VERSION%
        cp -r bin QuiteRSS-%APPVEYOR_BUILD_VERSION%
        echo > QuiteRSS-%APPVEYOR_BUILD_VERSION%\portable.dat
        7z a "QuiteRSS-%APPVEYOR_BUILD_VERSION%.zip" "QuiteRSS-%APPVEYOR_BUILD_VERSION%"
     )
     if "%PORTABLE%" == "false" (
        echo "test2"
        if "%APPVEYOR_REPO_TAG%" == "true" (
            mkdir QuiteRSS-%APPVEYOR_BUILD_VERSION%-setup-%ARCH%
        )
     )

artifacts:
  - path: build\QuiteRSS-%APPVEYOR_BUILD_VERSION%.zip
    name: QuiteRSS-portable
  - path: build\QuiteRSS-%APPVEYOR_BUILD_VERSION%-setup-%ARCH%.exe
    name: QuiteRSS-setup

deploy:
- provider: BinTray
  username: funcy-dcm
  api_key:
    secure: pHgpq9FPGqcuEERtIZJAEvkEXUzl2OwVmcw4j8z5ndngGXBGRiRXzbBBTSAFef5n
  subject: quiterss
  repo: quiterss2
  package: Windows-installer
  version: $(APPVEYOR_BUILD_VERSION)
  publish: true
  override: true
  artifact: QuiteRSS-setup
  on:
    appveyor_repo_tag: true
  
- provider: BinTray
  username: funcy-dcm
  api_key:
    secure: pHgpq9FPGqcuEERtIZJAEvkEXUzl2OwVmcw4j8z5ndngGXBGRiRXzbBBTSAFef5n
  subject: quiterss
  repo: quiterss2
  package: Windows-portable
  version: $(APPVEYOR_BUILD_VERSION)
  publish: true
  override: true
  artifact: QuiteRSS-portable
  on:
    appveyor_repo_tag: true
  
- provider: BinTray
  username: funcy-dcm
  api_key:
    secure: pHgpq9FPGqcuEERtIZJAEvkEXUzl2OwVmcw4j8z5ndngGXBGRiRXzbBBTSAFef5n
  subject: quiterss
  repo: quiterss2-development
  package: Windows-portable-dev
  version: $(APPVEYOR_BUILD_VERSION)
  publish: true
  override: true
  artifact: QuiteRSS-portable
  on:
    branch: master
