dist: trusty
sudo: required
language: cpp
cache: ccache

matrix:
  include:
    - os: osx
      osx_image: xcode8.3

    - os: linux

compiler:
 - gcc
 - clang
 
env:
 - QT=qt59
 
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update;
      sudo apt-get -qq install libssl-dev pkg-config libxcb-util0-dev;
      sudo apt-add-repository -y ppa:beineri/opt-qt59-trusty;
      sudo apt-get update -qq;
      sudo apt-get install -qq qt59tools qt58base qt59webengine qt59webchannel;

    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Calling brew update...";
      brew update;
      brew outdated openssl || brew upgrade openssl;
      brew install ccache;
      PATH="/usr/local/opt/ccache/libexec:$PATH";

#      if [[ "$QT" == "qt59" ]]; then
#        QT_VER=5.9;
#        if [ -z "$TRAVIS_TAG" ]; then
          echo "Using Homebrew Qt...";
          brew install qt5;
          export QTDIR=/usr/local/opt/qt5;
#        else
#          echo "Using official Qt installer...";
#          QT_INSTALLER_FILE_NAME=qt-opensource-mac-x64-clang-$QT_VER.0;
#          wget "http://download.qt.io/official_releases/qt/$QT_VER/$QT_VER.0/$QT_INSTALLER_FILE_NAME.dmg";
#          hdiutil attach -noverify $QT_INSTALLER_FILE_NAME.dmg;
#          QT_INSTALLER=/Volumes/$QT_INSTALLER_FILE_NAME/$QT_INSTALLER_FILE_NAME.app/Contents/MacOS/$QT_INSTALLER_FILE_NAME;
#          echo "Silently installing Qt...";
#          travis_wait $QT_INSTALLER --script $PWD/mac/qt-mac-silent-install.qs;
#          export QTDIR="$HOME/Qt/$QT_VER/clang_64";
#        fi
      fi
    fi

script:
  - QMAKE="qmake"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      CXXFLAGS="-Wextra -Werror";
      QMAKE="/opt/qt59/bin/qmake";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      CXXFLAGS="-Wextra -Werror -Wno-inconsistent-missing-override -Wno-deprecated-declarations";
      QMAKE=$QTDIR/bin/qmake;
    fi
  - $QMAKE QMAKE_CXXFLAGS+="$CXXFLAGS"
  - make -j2 CC=$CC CXX=$CXX || exit 1
  - make install
  - ccache --show-stats
