dist: trusty
sudo: required
language: cpp
cache: ccache

matrix:
  include:
    - os: linux
      compiler:
        - gcc
      env:
        - BUILD_ENV=linux_gcc
    - os: linux
      compiler:
        - clang
      env:
        - BUILD_ENV=linux_clang
        
    - os: osx
      osx_image: xcode8.3
      compiler:
        - gcc
      env:
        - BUILD_ENV=osx_gcc
    - os: osx
      osx_image: xcode8.3
      compiler:
        - clang
      env:
        - BUILD_ENV=osx_clang

before_install:
  - if [ -z "$TRAVIS_TAG" ]; then
      export BULD_VER=build${TRAVIS_BUILD_NUMBER}-${TRAVIS_BRANCH};
    else
      export BULD_VER=${TRAVIS_TAG};
    fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update;
      sudo apt-get -qq install libssl-dev pkg-config libxcb-util0-dev;
      sudo apt-add-repository -y ppa:beineri/opt-qt59-trusty;
      sudo apt-get update -qq;
      sudo apt-get install -qq qt59tools qt59base qt59webengine qt59webchannel;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Calling brew update...";
      brew update;
      brew outdated openssl || brew upgrade openssl;
      brew install ccache;
      PATH="/usr/local/opt/ccache/libexec:$PATH";
      echo "Using Homebrew Qt...";
      brew install qt5;
      export QTDIR=/usr/local/opt/qt5;
    fi

script:
  - QMAKE="qmake"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      QMAKE="/opt/qt59/bin/qmake";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      QMAKE=$QTDIR/bin/qmake;
      MACDEPLOYQT=$QTDIR/bin/macdeployqt;
    fi
  - mkdir build && cd build
  - $QMAKE -r ..
  - make -j3 CC=$CC CXX=$CXX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      $MACDEPLOYQT quiterss2.app -dmg;
      mv quiterss2.dmg QuiteRSS-${BULD_VER}.dmg;
    fi
  - ccache --show-stats
  
after_success:
  - if [[ "$BUILD_ENV" == "osx_clang" ]]; then
      ls;
      ls ../;
      ../tools/build/bintray-macosx-dev-upload.sh;
    fi

#deploy:
#  - provider: script
#    script: ./tools/build/bintray-macosx-dev-upload.sh
#    skip_cleanup: true
#    on:
#      branch: master
#      tags: false
#      condition: $BUILD_ENV = osx_clang
#  - provider: script
#    script: ../tools/build/bintray-macosx-dev-upload.sh
#    skip_cleanup: true
#    on:
#      branch: master
#      tags: false
#      condition: $BUILD_ENV = osx_gcc
