dist: trusty
sudo: required
language: cpp
cache: ccache

matrix:
  include:
    - os: linux
      compiler:
        - gcc
      env:
        - QT=qt59 && CC=gcc
    - os: linux
      compiler:
        - clang
      env:
        - QT=qt59 && CC=clang
        
    - os: osx
      osx_image: xcode8.3
      compiler:
        - gcc
      env:
        - QT=qt59 && CC=gcc
    - os: osx
      osx_image: xcode8.3
      compiler:
        - clang
      env:
        - QT=qt59 && CC=clang

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get -qq update;
      sudo apt-get -qq install libssl-dev pkg-config libxcb-util0-dev;
      sudo apt-add-repository -y ppa:beineri/opt-qt59-trusty;
      sudo apt-get update -qq;
      sudo apt-get install -qq qt59tools qt59base qt59webengine qt59webchannel;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "Calling brew update...";
      brew update;
      brew outdated openssl || brew upgrade openssl;
      brew install ccache;
      PATH="/usr/local/opt/ccache/libexec:$PATH";
      echo "Using Homebrew Qt...";
      brew install qt5;
      export QTDIR=/usr/local/opt/qt5;
    fi

script:
  - QMAKE="qmake"
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      CXXFLAGS="-Wextra -Werror";
      QMAKE="/opt/qt59/bin/qmake";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      CXXFLAGS="-Wextra -Werror -Wno-inconsistent-missing-override -Wno-deprecated-declarations";
      QMAKE=$QTDIR/bin/qmake;
    fi
  - $QMAKE QMAKE_CXXFLAGS+="$CXXFLAGS"
  - make -j2 CC=$CC CXX=$CXX || exit 1
  - make install
  - ccache --show-stats
